/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\
|  Phycas: Python software for phylogenetic analysis						  |
|  Copyright (C) 2006 Mark T. Holder, Paul O. Lewis and David L. Swofford	  |
|																			  |
|  This program is free software; you can redistribute it and/or modify		  |
|  it under the terms of the GNU General Public License as published by		  |
|  the Free Software Foundation; either version 2 of the License, or		  |
|  (at your option) any later version.										  |
|																			  |
|  This program is distributed in the hope that it will be useful,			  |
|  but WITHOUT ANY WARRANTY; without even the implied warranty of			  |
|  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the			  |
|  GNU General Public License for more details.								  |
|																			  |
|  You should have received a copy of the GNU General Public License along	  |
|  with this program; if not, write to the Free Software Foundation, Inc.,	  |
|  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.				  |
\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

#include <boost/shared_ptr.hpp>
#include "ncl/nxspublicblocks.h"
#include "nxs_file_path.hpp"
#include "char_super_matrix.hpp"

enum CmdResult
	{
	kCmdSucceeded,
	kCmdFailedSilent,
	kCmdFailedGenerateMessage
	};

class PhycasNexusReader: public PublicNexusReader
	{
	public:
		PhycasNexusReader(const int blocksToRead, NxsReader::WarningHandlingMode mode=NxsReader::WARNINGS_TO_STDERR)
			:PublicNexusReader(blocksToRead, mode),
			activeTaxaBlockIndex(UINT_MAX),
			activeCharactersBlockIndex(UINT_MAX)
			{
			this->SetWarningOutputLevel(SKIPPING_CONTENT_WARNING);
            this->GetTreesBlockTemplate()->SetTreatAsRootedByDefault(false);

			// UNCOMMON_SYNTAX_WARNING = 0,  /**< Legal but uncommon syntax that could indicate a typo */
			// SKIPPING_CONTENT_WARNING = 1, /**< Content is being skipped by NCL */ <-- default value
			// OVERWRITING_CONTENT_WARNING = 2, /**< New content is replacing old information (eg. CharSets with the same name as a previously defined CharSet)*/
			// DEPRECATED_WARNING = 3, /**< Use of a deprecated feature */
			// AMBIGUOUS_CONTENT_WARNING = 4, /**< commands that could have multiple plausible interpretations */
			// ILLEGAL_CONTENT_WARNING = 5, /**< content that violates NEXUS rules, but is still parseable (eg. CharPartitions that only have some of the characters)*/
			// PROBABLY_INCORRECT_CONTENT_WARNING = 6, /**< Severe Warning that is generated when the file contains characters that should almost certainly be removed */
			// FATAL_WARNING = 7, /**< a higher warning level then any of the warning generated by NCL.  Primarily used in constructs such as (FATAL_WARNING - 1) to mean only the most severe warnings.*/
			// SUPPRESS_WARNINGS_LEVEL = 8 /**<  if the NxsReader's warning level is set to this, then warnings will be suppressed */
            // std::cerr << ">>>> warning level >>>> " << GetWarningOutputLevel() << std::endl;
            SetWarningOutputLevel(NxsReader::FATAL_WARNING);
			}

		~PhycasNexusReader();

		void ReadFilePath(const std::string & filePath)
			{
			NxsInFilePath fp(filePath);
			ReadNxsFilePath(fp);
			}

		std::vector<std::string> GetTaxLabels() const;

		const std::vector<NxsFullTreeDescription> & GetTrees() const;

		unsigned GetNChar() const;

		std::string GetErrorMessage()
			{
			return errorMsg;
			}

		virtual void Clear();

		virtual void ClearUsedBlockList()
			{
			PublicNexusReader::ClearUsedBlockList();
			activeTaxaBlockIndex = UINT_MAX;
			activeCharactersBlockIndex = UINT_MAX;
			}

		NxsCharactersBlock * getActiveCharactersBlock() const;

		//virtual void NexusError(const std::string &msg, file_pos pos, unsigned line, unsigned col, CmdResult , NxsBlock* );

	private:

		void								ReadNxsFilePath(NxsInFilePath & filePath);
		NxsTaxaBlock *						getActiveTaxaBlock() const;

		std::string							errorMsg;
		unsigned 							activeTaxaBlockIndex;
		std::vector<NxsFullTreeDescription>	trees;
		unsigned 							activeCharactersBlockIndex;
		file_pos							filePositionOfError;
		//unsigned							lineOfError ;
		//unsigned							columnOfError ;

	};


typedef boost::shared_ptr<PhycasNexusReader> PhycasNexusReaderShPtr;

